[package]
name = "startpage"
version = "0.1.0"
authors = ["simon-wf <simonwoodburyforget@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
ron = "0.5.1"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
dirs-next = "1"
